/**
 * Cloudinary configuration and URL helper utilities.
 * API secret is loaded from environment variables only — never hardcoded.
 */

const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME ?? "zktumplt";

// ----- URL builders (safe everywhere) ----------------------------------------

/**
 * Build a Cloudinary image delivery URL from a public_id.
 * Applies f_auto,q_auto by default for optimal delivery.
 */
export function cloudinaryUrl(
  publicId: string,
  options: {
    width?: number;
    height?: number;
    crop?: string;
    quality?: string;
    format?: string;
    transforms?: string;
  } = {}
): string {
  const {
    width,
    height,
    crop = "fill",
    quality = "auto",
    format = "auto",
    transforms,
  } = options;

  const parts: string[] = [`f_${format}`, `q_${quality}`];
  if (width) parts.push(`w_${width}`);
  if (height) parts.push(`h_${height}`);
  if ((width || height) && crop) parts.push(`c_${crop}`);
  if (transforms) parts.push(transforms);

  return `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/${parts.join(",")}/${publicId}`;
}

/**
 * Build a Cloudinary video delivery URL from a public_id.
 */
export function cloudinaryVideoUrl(
  publicId: string,
  options: { quality?: string; format?: string } = {}
): string {
  const { quality = "auto", format = "auto" } = options;
  return `https://res.cloudinary.com/${CLOUD_NAME}/video/upload/f_${format},q_${quality}/${publicId}`;
}

// ----- Mapping (Server Components only) --------------------------------------

/**
 * Read the url-mapping.json generated by `npm run migrate:media`.
 * Returns an empty object if the file doesn't exist yet.
 * MUST only be called from Server Components or Node.js scripts — not from
 * client components or "use client" modules.
 */
function readUrlMapping(): Record<string, string> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("fs") as typeof import("fs");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("path") as typeof import("path");
    const mappingPath = path.join(process.cwd(), "migration/url-mapping.json");
    if (!fs.existsSync(mappingPath)) return {};
    return JSON.parse(fs.readFileSync(mappingPath, "utf-8"));
  } catch {
    return {};
  }
}

/**
 * Resolve a WordPress media URL to its Cloudinary counterpart (server-only).
 * Returns the original WP URL as a fallback if the mapping doesn't exist.
 *
 * Use this in Server Components and in lib functions called at build time.
 * For client components, pass the resolved URL down as a prop.
 */
export function resolveImageUrl(
  wpUrl: string,
  options: Parameters<typeof cloudinaryUrl>[1] = {}
): string {
  const mapping = readUrlMapping();
  const cloudinarySecureUrl = mapping[wpUrl];

  if (cloudinarySecureUrl) {
    // The mapping stores the full Cloudinary URL (e.g. from upload result).
    // If options are provided, we need to inject the transformation.
    const { width, height, crop = "fill", quality = "auto", format = "auto" } =
      options;
    if (width || height) {
      const parts = [`f_${format}`, `q_${quality}`];
      if (width) parts.push(`w_${width}`);
      if (height) parts.push(`h_${height}`);
      if (crop) parts.push(`c_${crop}`);
      // Insert transformation into the Cloudinary URL
      return cloudinarySecureUrl.replace(
        "/upload/",
        `/upload/${parts.join(",")}/`
      );
    }
    return cloudinarySecureUrl;
  }

  // Fallback: original WordPress URL (works before migrate:media is run)
  return wpUrl;
}

/**
 * Resolve a WordPress video URL to Cloudinary (server-only).
 * Falls back to the original WP URL if not migrated yet.
 */
export function resolveVideoUrl(wpUrl: string): string {
  const mapping = readUrlMapping();
  return mapping[wpUrl] ?? wpUrl;
}
